# Site settings
title: Yet Another Homepage | Anna Tikhonova
email: anna.m.surname@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://atikhono.github.io" # the base hostname & protocol for your site
github_username: atikhono

paginate: 10

# Build settings
markdown: kramdown
